version: '3.7'

services:
  database:
    container_name: zepartner_database
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./.docker/db/mongodb:/data/db
      - ./.docker/db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js'
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'zepartner'
      MONGO_INITDB_ROOT_PASSWORD: 'zepartner'
      MONGO_INITDB_DATABASE: 'partners'
  app:
    container_name: zepartner
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - .:/usr/app
    env_file:
      - .env
    links:
      - database
    depends_on:
      - database
    
